<?php

namespace App\Mainframe\Modules\Subscriptions\Traits;

use App\Subscription;
use App\Mainframe\Modules\Subscriptions\SubscriptionProcessor;

/** @mixin SubscriptionProcessor $this */
trait SubscriptionProcessorTrait
{
    /*
   |--------------------------------------------------------------------------
   | Fill model .
   |--------------------------------------------------------------------------
   |
   | Sometimes you need to automatically fill some fields of a model based
   | on known logic. For example: if you can take first_name and last_name
   | of an user and auto fill full_name.
   */

    /**
     * Fill the model with values
     *
     * @param  \App\Subscription  $subscription
     * @return $this
     */
    public function fill($subscription)
    {
        return $this;
    }

    /*
    |--------------------------------------------------------------------------
    | Rules.
    |--------------------------------------------------------------------------
    |
    | Write the laravel validation rules
    */

    /**
     * Validation rules.
     *
     * @param  \App\Subscription  $subscription
     * @param  array  $merge
     * @return array
     */
    public static function rules($subscription, $merge = [])
    {
        $rules = [
            'name' => 'required|between:1,255|unique:subscriptions,name,'.(isset($subscription->id) ? (string) $subscription->id : 'null').',id,deleted_at,NULL',
            'is_active' => 'in:1,0',
        ];

        return array_merge($rules, $merge);
    }

    /**
     * Custom error messages.
     *
     * @param  array  $merge
     * @return array
     */
    public static function customErrorMessages($merge = [])
    {
        $messages = [];

        return array_merge($messages, $merge);
    }

    /*
    |--------------------------------------------------------------------------
    | Execute validation on module events
    |--------------------------------------------------------------------------
    |
    | Check validations on saving, creating, updating, deleting and restoring
    */

    /**
     * Run validations for saving. This should be common for both creating and updating.
     *
     * @param  Subscription  $subscription
     * @return $this
     */
    public function saving($subscription)
    {

        return $this;
    }

    // /**
    //  * Creating validation
    //  *
    //  * @param $subscription \App\Mainframe\Modules\Superheroes\Subscription
    //  * @return \App\Mainframe\Features\Modular\Validator\ModelValidator|\App\Mainframe\Modules\Settings\SettingValidator
    //  */
    // public function creating($subscription)
    // {
    //     return parent::creating($subscription); // TODO: Change the autogenerated stub
    // }
    //
    // /**
    //  * Updating validation
    //  *
    //  * @param $subscription \App\Mainframe\Modules\Superheroes\Subscription
    //  * @return \App\Mainframe\Features\Modular\Validator\ModelValidator|\App\Mainframe\Modules\Settings\SettingValidator
    //  */
    // public function updating($subscription)
    // {
    //     return parent::updating($subscription); // TODO: Change the autogenerated stub
    // }
    //
    // /**
    //  *  Deleting validation
    //  *
    //  * @param $subscription \App\Mainframe\Modules\Superheroes\Subscription
    //  * @return \App\Mainframe\Features\Modular\Validator\ModelValidator|\App\Mainframe\Modules\Settings\SettingValidator
    //  */
    // public function deleting($subscription)
    // {
    //     return parent::deleting($subscription); // TODO: Change the autogenerated stub
    // }
    //
    // /**
    //  * Restoring validation
    //  *
    //  * @param $subscription \App\Mainframe\Modules\Superheroes\Subscription
    //  * @return \App\Mainframe\Features\Modular\Validator\ModelValidator|\App\Mainframe\Modules\Settings\SettingValidator
    //  */
    // public function restoring($subscription)
    // {
    //     return parent::restoring($subscription); // TODO: Change the autogenerated stub
    // }

    /*
    |--------------------------------------------------------------------------
    | Validation helper functions
    |--------------------------------------------------------------------------
    |
    | All validation must be checked through some function. All validation
    | functions are listed below.
    */

}