<?php

namespace App\Mainframe\Modules\Tenants\Traits;

use App\Mainframe\Modules\Tenants\TenantProcessor;

/** @mixin TenantProcessor $this */
trait TenantProcessorTrait
{

    /*
    |--------------------------------------------------------------------------
    | Fill model .
    |--------------------------------------------------------------------------
    |
    | Sometimes you need to automatically fill some fields of a model based
    | on known logic. For example: if you can take first_name and last_name
    | of an user and auto fill full_name.
    */

    /**
     * Fill the model with values
     *
     * @param  \App\Tenant  $tenant
     * @return $this
     */
    public function fill($tenant)
    {
        return $this;
    }

    /*
    |--------------------------------------------------------------------------
    | Rules.
    |--------------------------------------------------------------------------
    |
    | Write the laravel validation rules
    */

    /**
     * Validation rules.
     *
     * @param  \App\Tenant  $tenant
     * @param  array  $merge
     * @return array
     */
    public static function rules($tenant, $merge = [])
    {
        $rules = [
            'name' => 'required|between:1,255|unique:tenants,name,'.(isset($tenant->id) ? (string) $tenant->id : 'null').',id,deleted_at,NULL',
            'is_active' => 'in:1,0',
        ];

        return array_merge($rules, $merge);
    }

    /**
     * Custom error messages.
     *
     * @param  array  $merge
     * @return array
     */
    public static function customErrorMessages($merge = [])
    {
        $messages = [];

        return array_merge($messages, $merge);
    }

    /*
    |--------------------------------------------------------------------------
    | Execute validation on module events
    |--------------------------------------------------------------------------
    |
    | Check validations on saving, creating, updating, deleting and restoring
    */

    /**
     * Run validations for saving. This should be common for both creating and updating.
     *
     * @param $tenant \App\Mainframe\Modules\Superheroes\Tenant
     * @return $this
     */
    public function saving($tenant)
    {

        return $this;
    }

    // /**
    //  * Creating validation
    //  *
    //  * @param $tenant \App\Mainframe\Modules\Superheroes\Tenant
    //  * @return \App\Mainframe\Features\Modular\Validator\ModelValidator|\App\Mainframe\Modules\Settings\SettingValidator
    //  */
    // public function creating($tenant)
    // {
    //     return parent::creating($tenant); // TODO: Change the autogenerated stub
    // }
    //
    // /**
    //  * Updating validation
    //  *
    //  * @param $tenant \App\Mainframe\Modules\Superheroes\Tenant
    //  * @return \App\Mainframe\Features\Modular\Validator\ModelValidator|\App\Mainframe\Modules\Settings\SettingValidator
    //  */
    // public function updating($tenant)
    // {
    //     return parent::updating($tenant); // TODO: Change the autogenerated stub
    // }
    //
    // /**
    //  *  Deleting validation
    //  *
    //  * @param $tenant \App\Mainframe\Modules\Superheroes\Tenant
    //  * @return \App\Mainframe\Features\Modular\Validator\ModelValidator|\App\Mainframe\Modules\Settings\SettingValidator
    //  */
    // public function deleting($tenant)
    // {
    //     return parent::deleting($tenant); // TODO: Change the autogenerated stub
    // }
    //
    // /**
    //  * Restoring validation
    //  *
    //  * @param $tenant \App\Mainframe\Modules\Superheroes\Tenant
    //  * @return \App\Mainframe\Features\Modular\Validator\ModelValidator|\App\Mainframe\Modules\Settings\SettingValidator
    //  */
    // public function restoring($tenant)
    // {
    //     return parent::restoring($tenant); // TODO: Change the autogenerated stub
    // }

    /*
    |--------------------------------------------------------------------------
    | Validation helper functions
    |--------------------------------------------------------------------------
    |
    | All validation must be checked through some function. All validation
    | functions are listed below.
    */

}