<?php

namespace App\Mainframe\Modules\Countries\Traits;

use App\Country;
use App\Mainframe\Modules\Countries\CountryProcessor;

/** @mixin CountryProcessor $this */
trait CountryProcessorTrait
{
    /*
        |--------------------------------------------------------------------------
        | Fill model .
        |--------------------------------------------------------------------------
        |
        | Sometimes you need to automatically fill some fields of a model based
        | on known logic. For example: if you can take first_name and last_name
        | of an user and auto fill full_name.
        */

    /**
     * Fill the model with values
     *
     * @param  \App\Country  $country
     * @return $this
     */
    public function fill($country)
    {
        parent::fill($country);

        // $country->name = 'Lorem Ipsum';

        return $this;
    }

    /*
    |--------------------------------------------------------------------------
    | Rules.
    |--------------------------------------------------------------------------
    |
    | Write the laravel validation rules
    */

    /**
     * Validation rules.
     *
     * @param  \App\Country  $country
     * @param  array  $merge
     * @return array
     */
    public static function rules($country, $merge = [])
    {
        $rules = [
            'name' => 'required|between:1,255|unique:countries,name,'.(isset($country->id) ? (string) $country->id : 'null').',id,deleted_at,NULL',
            'is_active' => 'in:1,0',
        ];

        return array_merge($rules, $merge);
    }

    /**
     * Custom error messages.
     *
     * @param  array  $merge
     * @return array
     */
    public static function customErrorMessages($merge = [])
    {
        $messages = [];

        return array_merge($messages, $merge);
    }

    /*
    |--------------------------------------------------------------------------
    | Execute validation on module events
    |--------------------------------------------------------------------------
    |
    | Check validations on saving, creating, updating, deleting and restoring
    */

    /**
     * Run validations for saving. This should be common for both creating and updating.
     *
     * @param  Country  $country
     * @return $this
     */
    public function saving($country)
    {
        parent::saving($country);

        /*
        |--------------------------------------------------------------------------
        | Call validation functions one by one.
        |--------------------------------------------------------------------------
        |
        | A list of functions that will be called sequentially to validate the model
        */

        return $this;
    }

    // /**
    //  * Creating validation
    //  *
    //  * @param $country \App\Mainframe\Modules\Superheroes\Country
    //  * @return \App\Mainframe\Features\Modular\Validator\ModelValidator|\App\Mainframe\Modules\Settings\SettingValidator
    //  */
    // public function creating($country)
    // {
    //     return parent::creating($country); // TODO: Change the autogenerated stub
    // }
    //
    // /**
    //  * Updating validation
    //  *
    //  * @param $country \App\Mainframe\Modules\Superheroes\Country
    //  * @return \App\Mainframe\Features\Modular\Validator\ModelValidator|\App\Mainframe\Modules\Settings\SettingValidator
    //  */
    // public function updating($country)
    // {
    //     return parent::updating($country); // TODO: Change the autogenerated stub
    // }
    //
    // /**
    //  *  Deleting validation
    //  *
    //  * @param $country \App\Mainframe\Modules\Superheroes\Country
    //  * @return \App\Mainframe\Features\Modular\Validator\ModelValidator|\App\Mainframe\Modules\Settings\SettingValidator
    //  */
    // public function deleting($country)
    // {
    //     return parent::deleting($country); // TODO: Change the autogenerated stub
    // }
    //
    // /**
    //  * Restoring validation
    //  *
    //  * @param $country \App\Mainframe\Modules\Superheroes\Country
    //  * @return \App\Mainframe\Features\Modular\Validator\ModelValidator|\App\Mainframe\Modules\Settings\SettingValidator
    //  */
    // public function restoring($country)
    // {
    //     return parent::restoring($country); // TODO: Change the autogenerated stub
    // }

    /*
    |--------------------------------------------------------------------------
    | Validation helper functions
    |--------------------------------------------------------------------------
    |
    | All validation must be checked through some function. All validation
    | functions are listed below.
    */

}